= Config Server
:toc:


== Externalized configuration

The server is embeddable in a Spring Boot application, by using the `@EnableConfigServer` annotation.

	@SpringBootApplication
	@EnableConfigServer
	public class ConfigServerApplication { ... } 
	
Like all Spring Boot applications, it runs on port `8080` by default, but you can switch it to the more conventional port `8888` in `application.properties` file.

	server.port: 8888
	spring.cloud.config.server.git.uri: file://${user.home}/config-repo
	
where `${user.home}/config-repo` is a git repository containing YAML and properties files (https://github.com/wanderleisouza/config-repo for me).

The following listing shows a recipe for creating the git repository in the preceding example:

	mkdir config-repo
	cd config-repo
	git init .
	echo info.foo: bar > application.properties
	git add -A .
	git commit -m "Add application.properties"
	git remote add origin git@github.com:wanderleisouza/config-repo.git
	git push -u origin master
	
just start ther *config-server* as any spring-boot application

	mvn spring-boot:run
